### ISSUE TITLE
Question about the acai embedding of omniglot

### ISSUE THREAD

**Issue by Howardqlz** [hsukyle/cactus-maml#12]
I wonder whether the label in the acai embedding of omniglot which you release is the same as the original? Like sample with label 719 refers to the 0719_x.png from the original dataset. Cause i want to use the acai embedding to do the normal classification on the original 50 tasks.
Wish your feedback!:)

**Comment by kylehkhsu** [comment]
I believe I shuffled the labels, so this is **not** the case. In other words, if you use e.g. Pillow to look at one of my samples with label 719, and compare to 0719_x.png, the characters should be different.

I encourage you to head to [https://github.com/brain-research/acai](url) to recreate your own Omniglot ACAI embeddings.
