### ISSUE TITLE
Metrics can be visualized using Tensorboard. ?

### ISSUE THREAD

**Issue by dragen1860** [hsukyle/cactus-maml#2]
Dear author:
  I found you stated `Metrics can be visualized using Tensorboard. ` in your readme.
However, I cant found the tensorflow log directory as follows:
![image](https://user-images.githubusercontent.com/4252555/46929096-6be6c300-d070-11e8-88c1-64a333c22dca.png)
Hence I dnt know how to run `tensorboard --logdir xxx`.

**Comment by kylehkhsu** [comment]
The tensorboard summaries, model checkpoints, and results are written to whatever you specify the --logdir flag to be. By default they're in some sub-directory of ./log.
