### ISSUE TITLE
influence on embeddings and clusters algorithm

### ISSUE THREAD

**Issue by dragen1860** [hsukyle/cactus-maml#4]
Dear author:
  Upon my current understanding towards your paper, I think the embedding and clusters algorithm(e.g. k-means) will have big influence on construction of tasks. Therefore, the constructed tasks will decide maml's performance finally.
 Let's talk a extreme case. If the embedding and cluster works really badly, then the construct tasks maybe relatively random. In that case, the task construction will be close to `naive approach` as stated in your paper below:
![image](https://user-images.githubusercontent.com/4252555/46991966-94d38a80-d13a-11e8-896c-6611e7690b20.png)
Hence it will lead to failing of meta-learning.

please address my doubts. Thanks.

**Comment by kylehkhsu** [comment]
I agree with your assessment. In the case you raise, the performance of the non-meta-learning methods that learn on top of the embeddings should also degrade.
