### ISSUE TITLE
why --num_classes_train != num_classes_val

### ISSUE THREAD

**Issue by dragen1860** [hsukyle/cactus-maml#5]
Hi, Dear author:
  I noticed the parameters `--num_classes_train=20 --num_classes_val=5 ` where num_classes_train is not the same with num_classes_val.
 I DNT understand this. As far as I know, the num_classes_train=`M`-way, which decides the dimension of last layer of maml. Therefore, in test phase, the network output dimension cant be changed and should keep the same.

**Comment by kylehkhsu** [comment]
During unsupervised meta-training we only assume knowledge of the upper bound of the number of classes in a downstream task. For Omniglot, we consider 5-way and 20-way tasks, so this upper bound is 20. We thus train on 20-way tasks. The mismatch is handled by simply throwing away the extra dimensions in the last layer at meta-test time.
