### ISSUE TITLE
cannot reproduce results on miniImagenet

### ISSUE THREAD

**Issue by xmengli** [hsukyle/cactus-maml#7]
Thanks for your paper and code. It is really a very good work!
I have some issues regarding to reproduce the results on miniImagenet. The reported results for 5way 1shot and 5 way 5 shot in the paper is 39.90% and 53.97%, but I only got 35.14% and 46.07%, respectively. 

Here is the details in my training procedures:
1, I trained deep clusters using authors code on miniImagenet. The "only" modification is that I changed the input size to 64*64 and (kernel_size, stride, padding)=(5,1,1) in the first conv layer of alexnet, as the procedures in section E.4 in the supplementary file.  The original (kernel_size, stride, padding) is (11,4,2). 
2, After training 1, I saved the embeddings of train, val, test dataset  to "./data/acai_encodings/miniimagenet_256_train.npz", "./data/acai_encodings/miniimagenet_256_val.npz", and 
"./data/acai_encodings/miniimagenet_256_test.npz". 
The 'X' in each encoding is the image, 'Y' is the label and 'Z' is the trained embeddings. 
So, in "miniimagenet_256_train.npz", X is (38400, 3, 84, 84), Y is (38400,) and Z is (38400, 256), where Z is trained with model from 1 and X,Y. is obtained from miniimagenet dataset. 
The embedding Z for "miniimagenet_256_val.npz" and "miniimagenet_256_test.npz" are obtained from the same model. (I donot know if it is necessary to train embedding for val, test dataset respectively ?)

3, Finally, I modified omniglot_kmeans.sh to miniimagenet dataset. I changed dataset to miniimagenet, modified num_partitions to 50, metatrain_iterations=60000, num_classes_train=5. The image size is 84*84*3. But I found the size is mismatch with network. So, I changed line 241 in maml.py to from 5*5 to 6*6. Then the network can be trained. But the results are different with those reported in the paper. 

I think I maybe wrong at some points. Please point out and give some more details for reproducing results. 

Many thanks for your contribution and help!!

**Comment by xmengli** [comment]
I also run the experiments on embeddings. But the results are worse. 
Looking forward to get your reply..

**Comment by xw-hu** [comment]
I also have the same problem.....

**Comment by kylehkhsu** [comment]
Hi there,

Thanks for the interest in this work. I'm very sorry to have not responded for such a lengthy period of time. 

I'll first congratulate you on the results you achieved -- they beat my embedding+supervised learning baselines, and that wasn't easy for me to do. If you're still interested in reproduction of my results, I've updated the repository to include the miniImageNet DeepCluster embeddings I used, as well as a script for running this experiment.

Feel free to re-open this issue should you feel the need.
