### ISSUE TITLE
Can you share pretrained models?

### ISSUE THREAD

**Issue by shaform** [hsukyle/cactus-maml#9]
In that case, we could directly reproduce the results as well as experiment with the clusters, embeddings etc.

**Comment by kylehkhsu** [comment]
Hi there,

You can directly reproduce results, including obtaining trained models, by running the existing code with the provided embeddings. The lengthiest experiment (60,000 iterations) takes just 5 hours to run with a single GPU. Clusters can be obtained from the embeddings in just a couple of minutes, also using the provided code. 

Feel free to re-open this issue should you feel the need.
